#!/usr/bin/perl -w

# Set up environment
use lib "/usr/lib/smoothwall";
use SmoothInstall qw( :standard );
use header  qw( :standard );
use Shell qw(rm);
use File::Path;
use Term::ANSIColor;

Init("backupssh");

# Start Uninstallation
ClearScreen;

print colored("Uninstalling ", "green");
print colored("$ModDetails{'MOD_NAME'} ", "cyan");
print colored("Version: ", "green");
print colored("$ModDetails{'MOD_VERSION'} \n", "magenta");
print colored("Restoring cgi script... \n", "green");
system("/bin/cp $MODDIR/backup/backup.img /httpd/cgi-bin");
system("chmod 755 /httpd/cgi-bin/backup.img");
rmtree("$MODDIR");
print colored("Finished Uninstallation. \n", "green");
