backupssh-create and transfer => Create backup and transfer to remote host >>
backupssh-warning => The remote host must have an SSH server running!
backupssh-popup1 => Re-install mod to change host name
backupssh-popup2 => Re-install mod to change user name
backupssh-popup3 => Keyfile generated in /root/.ssh at install time. Re-install mod to change
backupssh-hint1 => To restore the settings to your newly installed Smoothie, run the following code from the command line (the new firewall <b>will be rebooted</b>):
backupssh-hint2 => Hint: To replace your Smoothie, change its green IP via setup (if still operational), load its web GUI, copy this code and paste it in a putty console on the new machine. You can now retire your old firewall. Otherwise keep this line of code somewhere handy. ;-)
backupssh-hint3 => <b>Note:</b> this is a one line only command.
backupssh-link-tip => Browse to the BackupSSH Mod thread and check for updates.
